# Generated by Django 6.0.4 on 2026-07-10 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('c_name', models.CharField(max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('p_name', models.CharField(max_length=256)),
                ('age_min', models.IntegerField(null=True)),
                ('age_max', models.IntegerField(null=True)),
                ('p_amount', models.FloatField(default=0.0)),
                ('duration', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('t_id', models.AutoField(primary_key=True, serialize=False)),
                ('t_name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('v_id', models.AutoField(primary_key=True, serialize=False)),
                ('v_name', models.CharField(max_length=256)),
                ('domain', models.URLField()),
                ('has_sdp', models.BooleanField(default=False)),
                ('last_fetched', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact_Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.ForeignKey(db_column='c_id', on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='api.contact')),
            ],
        ),
        migrations.CreateModel(
            name='Contact_Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=16)),
                ('contact', models.ForeignKey(db_column='c_id', on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='api.contact')),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='p_id',
            field=models.ForeignKey(db_column='p_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='api.program'),
        ),
        migrations.AddField(
            model_name='program',
            name='v_id',
            field=models.ForeignKey(db_column='v_id', on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='api.vendor'),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('loc_id', models.AutoField(primary_key=True, serialize=False)),
                ('loc_name', models.CharField(max_length=256, null=True)),
                ('street', models.CharField(max_length=256)),
                ('city', models.CharField(max_length=256)),
                ('state', models.CharField(max_length=256)),
                ('zipcode', models.IntegerField()),
                ('p_id', models.ForeignKey(db_column='p_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='api.program')),
                ('v_id', models.ForeignKey(db_column='v_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_locations', to='api.vendor')),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='v_id',
            field=models.ForeignKey(db_column='v_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_contacts', to='api.vendor'),
        ),
    ]
