# Generated by Django 6.0.4 on 2026-07-10 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='zipcode',
            field=models.CharField(max_length=256),
        ),
    ]
